
GRPC_PORT: 8080
GRPC_ADDR: "0.0.0.0"
API_DB_DRIVER: "postgres"
API_DB_PORT: 5432
API_DB_HOST: "postgres"
API_DB_NAME: "postgres"
API_DB_USER: "postgres"
API_DB_PASS: "12345"
API_PQ_SSLMODE: "disable"
AUTH_TABLE: "users"
SHOP_BIND_ADDR: "0.0.0.0:8081"